### PR TITLE
add title field to Job model

### PR DESCRIPTION
**Pull request by imcaizheng**
- update ES mapping for the Job index
- update Joi schema

### CODE REVIEW

**Review by maxceem — APPROVED** [review]
@imcaizheng tested locally and works good.

**Comment by imcaizheng** [comment]
@maxceem Just in case, we may need to update existing ES server deployed for DEV similar with https://github.com/topcoder-platform/taas-apis/issues/22#issuecomment-737691144

**Comment by maxceem** [comment]
Thanks for pointing this out @imcaizheng. As per discussion in that ticket it looks like AWS ES doesn't support such commands, so for existent data, we would not have `title` for now. I think we have to create a script that would reindex all the data from DB to ES to handle such situations in the future.

**Comment by maxceem** [comment]
@imcaizheng but we still have to updated mapping, right?

**Comment by imcaizheng** [comment]
@maxceem Yes. It was confirmed by nkumar-topcoder that update mapping would work for AWS ES in this comment https://github.com/topcoder-platform/taas-apis/issues/22#issuecomment-737729368.

It seems like a workaround for migrating data from DB to ES every time indices are modified, but it is quite a solution for now.

**Pull request merged**
